name: "CI CD Android"
on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

  workflow_dispatch:

jobs:
  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$MAPS_MAPS_API_KEY" > ./local.properties

      - name: Run Test
        run: |
          ./gradlew test --stacktrace

  android_test:
    name: Run Instrumentation Test
    runs-on: macos-latest
    env:
      MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$MAPS_API_KEY" > ./local.properties

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

  build:
    runs-on: ubuntu-latest
    needs: [unit_test, android_test]
    env:
      MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: setup local.properties
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$MAPS_API_KEY" > ./local.properties

      - name: Build APK
        run: ./gradlew build

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get build info
        id: build_info
        run: echo "::set-output name=version-name::$(bash ./gradlew -q printVersionName)"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Build Artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: release-${{ steps.build_info.outputs.version-name }}
          release_name: Release v${{ steps.build_info.outputs.version-name }}

      - name: Upload APK to release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/zip
